/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/accounts": {
    /** Create a new Account by supplying basic information */
    get: operations["ListAccounts"];
    /** Create a new Account by supplying basic information */
    post: operations["CreateAccount"];
  };
  "/accounts/{id}": {
    get: operations["GetAccount"];
  };
  "/accounts/{id}/roles": {
    /** Create a role under an account for a role or application */
    post: operations["CreateAccountRole"];
  };
  "/accounts/{id}/policy": {
    post: operations["CreatePolicy"];
  };
  "/accounts/{id}/invite": {
    post: operations["InviteAccountUser"];
  };
  "/accounts/{id}/applications": {
    /** Create a new Account application */
    post: operations["CreateAccountApplication"];
  };
  "/users": {
    /** Create a new User by supplying login credentials at a minimum */
    post: operations["CreateUser"];
  };
  "/authenticate": {
    /** Authenticate a user or application */
    post: operations["Authenticate"];
  };
}

export interface components {
  schemas: {
    AccountRequest: {
      /**
       * @description The name of the account
       * @example Johns Place
       */
      name: string;
      /** @description An optional short description of the account */
      description?: string;
    };
    CreateAccountResponse: {
      /**
       * Format: uuid
       * @description A generated unique identifier for the newly created account
       */
      id: string;
      /**
       * @description The name of the account
       * @example Johns Place
       */
      name: string;
      /** @description An optional short description of the account */
      description?: string;
    };
    AccountResponse: {
      /**
       * Format: uuid
       * @description A generated unique identifier for the newly created account
       */
      id: string;
      /**
       * @description The name of the account
       * @example Johns Place
       */
      name: string;
      /** @description An optional short description of the account */
      description?: string;
    };
    ListAccountResponse: components["schemas"]["AccountResponse"][];
    AccountRoleRequest: {
      /** @description The name of the role */
      name: string;
      /** @description A short summary of the responsibilities of the role */
      description?: string;
    };
    AccountRoleResponse: {
      /** @description The primary id for the account role */
      id: string;
      /** @description The name of the role */
      name: string;
      /** @description A short summary of the responsibilities of the role */
      description?: string;
    };
    UserRequest: {
      /**
       * @description The email address of the user being created
       * @example john@smith.co.uk
       */
      email: string;
      /** @description The password of the user being created */
      password: string;
      /**
       * @description The optional username of the user being created
       * @example JohnDoe89
       */
      username?: string;
      /** @description An optional short description of the account */
      accountId?: string;
    };
    UserResponse: {
      /**
       * Format: uuid
       * @description A generated unique identifier for the user
       */
      id: string;
      /**
       * @description The email address of the user being created
       * @example john@smith.co.uk
       */
      email: string;
      /**
       * @description The optional username of the user being created
       * @example JohnDoe89
       */
      username?: string;
      /** @description An optional short description of the account */
      accountId?: string;
    };
    AccountAppRequest: {
      /** @description The name of the account application */
      name: string;
      /** @description A description of the account application being created */
      description?: string;
    };
    CreateAccountAppResponse: {
      /**
       * Format: uuid
       * @description primary identifier for the created account application
       */
      id: string;
      /** @description The name of the account application */
      name: string;
      /**
       * Format: uuid
       * @description The id for the account this application is associated with
       */
      accountId: string;
      /**
       * Format: uuid
       * @description The client id for the application, should be exchanged for an access token via the authenticate endpoint in order to make authenticated requests to accessible apis.
       */
      clientId: string;
      /** @description The client secret for the application, should be exchanged with the clientId for an access token via the authenticate endpoint in order to make authenticated requests to accessible apis. MAKE SURE YOU COPY AND SAVE THIS VALUE, IT IS ONLY RETURNED ONCE AND CANNOT BE ACCESSED LATER. */
      clientSecret: string;
      /** @description A description of the account application being created */
      description?: string;
    };
    AuthenticateUser:
      | {
          email: string;
          password: string;
        }
      | {
          username: string;
          password: string;
        };
    AuthenticateApp: {
      clientId: string;
      clientSecret: string;
    };
    AuthenticateRes: {
      accessToken: string;
    };
    PolicyRequest: {
      content: { [key: string]: unknown };
    };
    PolicyResponse: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      accountId: string;
      content: { [key: string]: unknown };
    };
  };
}

export interface operations {
  /** Create a new Account by supplying basic information */
  ListAccounts: {
    responses: {
      /** Successful creation of an account */
      201: {
        content: {
          "application/json": components["schemas"]["ListAccountResponse"];
        };
      };
    };
  };
  /** Create a new Account by supplying basic information */
  CreateAccount: {
    parameters: {
      header: {
        authorization?: string;
      };
    };
    responses: {
      /** Successful creation of an account */
      201: {
        content: {
          "application/json": components["schemas"]["CreateAccountResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountRequest"];
      };
    };
  };
  GetAccount: {
    parameters: {
      path: {
        /** primary id of the account to be retrieved */
        id: string;
      };
    };
    responses: {
      /** Successful creation of an account */
      200: {
        content: {
          "application/json": components["schemas"]["AccountResponse"];
        };
      };
    };
  };
  /** Create a role under an account for a role or application */
  CreateAccountRole: {
    parameters: {
      header: {
        authorization?: string;
      };
    };
    responses: {
      /** Successful creation of an account policy */
      200: {
        content: {
          "application/json": components["schemas"]["AccountRoleResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountRoleRequest"];
      };
    };
  };
  CreatePolicy: {
    parameters: {
      path: {
        /** primary id of the account for the policy */
        id: string;
      };
    };
    responses: {
      /** Successful creation of an account policy */
      200: {
        content: {
          "application/json": components["schemas"]["PolicyResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PolicyRequest"];
      };
    };
  };
  InviteAccountUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Successfully created an email invite for a new user */
      200: unknown;
    };
  };
  /** Create a new Account application */
  CreateAccountApplication: {
    parameters: {
      path: {
        /** primary id for the account the application will belong to */
        id: string;
      };
    };
    responses: {
      /** Successful creation of an account */
      201: {
        content: {
          "application/json": components["schemas"]["CreateAccountAppResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountAppRequest"];
      };
    };
  };
  /** Create a new User by supplying login credentials at a minimum */
  CreateUser: {
    responses: {
      /** Successful creation of an account */
      201: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRequest"];
      };
    };
  };
  /** Authenticate a user or application */
  Authenticate: {
    responses: {
      /** Successful creation of an account */
      200: {
        content: {
          "application/json": components["schemas"]["AuthenticateRes"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json":
          | components["schemas"]["AuthenticateUser"]
          | components["schemas"]["AuthenticateApp"];
      };
    };
  };
}

export interface external {}
