/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/accounts": {
    /** Create a new Account by supplying basic information */
    post: operations["CreateAccount"];
  };
  "/accounts/{id}": {
    get: operations["GetAccount"];
  };
  "/users": {
    /** Create a new Account by supplying basic information */
    post: operations["CreateUser"];
  };
}

export interface components {
  schemas: {
    AccountRequest: {
      /**
       * @description The name of the account
       * @example Johns Place
       */
      name: string;
      /**
       * @description The email address of the account owner
       * @example john@smith.co.uk
       */
      email: string;
      /** @description The user password of the account owner */
      password: string;
      /** @description An optional short description of the account */
      description?: string;
    };
    CreateAccountResponse: {
      /**
       * Format: uuid
       * @description A generated unique identifier for the newly created account
       */
      id: string;
      /**
       * @description The name of the account
       * @example Johns Place
       */
      name: string;
      /**
       * @description The email address of the account owner
       * @example john@smith.co.uk
       */
      email: string;
      /** @description An optional short description of the account */
      description?: string;
    };
    AccountResponse: {
      /**
       * Format: uuid
       * @description A generated unique identifier for the newly created account
       */
      id: string;
      /**
       * @description The name of the account
       * @example Johns Place
       */
      name: string;
      /** @description An optional short description of the account */
      description?: string;
    };
    UserRequest: {
      /**
       * @description The email address of the user being created
       * @example john@smith.co.uk
       */
      email: string;
      /** @description The password of the user being created */
      password: string;
      /**
       * @description The optional username of the user being created
       * @example JohnDoe89
       */
      username?: string;
      /** @description An optional short description of the account */
      accountId?: string;
    };
    UserResponse: {
      /**
       * Format: uuid
       * @description A generated unique identifier for the user
       */
      id: string;
      /**
       * @description The email address of the user being created
       * @example john@smith.co.uk
       */
      email: string;
      /**
       * @description The optional username of the user being created
       * @example JohnDoe89
       */
      username?: string;
      /** @description An optional short description of the account */
      accountId?: string;
    };
  };
}

export interface operations {
  /** Create a new Account by supplying basic information */
  CreateAccount: {
    responses: {
      /** Successful creation of an account */
      201: {
        content: {
          "application/json": components["schemas"]["CreateAccountResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountRequest"];
      };
    };
  };
  GetAccount: {
    parameters: {
      path: {
        /** primary id, uuid of the account to be retrieved */
        id: string;
      };
    };
    responses: {
      /** Successful creation of an account */
      200: {
        content: {
          "application/json": components["schemas"]["AccountResponse"];
        };
      };
    };
  };
  /** Create a new Account by supplying basic information */
  CreateUser: {
    responses: {
      /** Successful creation of an account */
      201: {
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRequest"];
      };
    };
  };
}

export interface external {}
